### ISSUE TITLE
`gen_templates` fails in python and command line

### ISSUE THREAD

**Issue by Dradeliomecus** [alejoe91/MEArec#106]
Hi,

I'm trying to use MEArec, but I have not been able to generate templates (both in command line and python).

Here is the error message:
```python
mr.gen_templates("/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp", recompile=True, templates_tmp_folder="/mnt/raid0/tmp/tmp", verbose=True)
Using default parameters
Compiling NEURON models
  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Probe randomly set to: tetrode-mea-d
Setting n_jobs to 40 CPUs
Running with 40 jobs
Starting 3


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_ChC_cACint209_1 3/13


Starting 2


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_BTC_bAC217_1 2/13


  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 3
  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 2
Starting 6


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_MC_bAC217_1 6/13


Starting 1


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_BP_bAC217_1 1/13


  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 6
Starting 5


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_LBC_bAC217_1 5/13


  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 1
  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 5
Starting 11


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_TTPC1_cADpyr232_1 11/13


  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 11
Starting 9


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_SBC_bNAC219_1 9/13


  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line Starting 13
98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                

 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_UTPC_cADpyr232_1 13/13

 
                                    ^
SyntaxError: invalid syntax
Exiting 9
Starting 8


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_NGC_bNAC219_1 8/13


  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 13
  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 8
Starting 4


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_DBC_bAC217_1 4/13


Starting 12


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_TTPC2_cADpyr232_1 12/13


  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Starting 7


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_NBC_bAC217_1 7/13


Exiting 4
  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 12
  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 7
Starting 10


 /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/L5_STPC_cADpyr232_1 10/13


  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/simulate_cells.py", line 98
    print(f"{_command} {nmodl} {cell_folder / 'mods'}")
                                                     ^
SyntaxError: invalid syntax
Exiting 10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/generation_tools.py", line 249, in gen_templates
    tempgen.generate_templates()
  File "/export/home1/users/nsr/wyngaard/dev/MEArec/MEArec/MEArec/generators/templategenerator.py", line 263, in generate_templates
    raise FileNotFoundError(
FileNotFoundError: /mnt/raid0/tmp/tmp/physrot/tmp_50_tetrode-mea-d not found. Something went wrong in the template generation phase.
```

It is very weird because I get a SyntaxError message, but there is actually no syntax error. As you can see, this function works fine:
```python
from MEArec import simulate_cells
simulate_cells.compile_all_mechanisms(".config/mearec/1.8.0/cell_models/bbp")
/export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods
Mod files: "./CaDynamics_E2.mod" "./Ca_HVA.mod" "./Ca_LVAst.mod" "./Ca.mod" "./Ih.mod" "./Im.mod" "./K_Pst.mod" "./K_Tst.mod" "./Nap_Et2.mod" "./NaTa_t.mod" "./NaTs2_t.mod" "./ProbAMPANMDA_EMS.mod" "./ProbGABAAB_EMS.mod" "./SK_E2.mod" "./SKv3_1.mod"

Creating x86_64 directory for .o files.

COBJS=''
 -> Compiling mod_func.cpp
 -> NMODL ../CaDynamics_E2.mod
 -> NMODL ../Ca_HVA.mod
 -> NMODL ../Ca_LVAst.mod
Translating CaDynamics_E2.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/CaDynamics_E2.c
Translating Ca_HVA.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/Ca_HVA.c
Translating Ca_LVAst.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/Ca_LVAst.c
Thread Safe
Thread Safe
Thread Safe
 -> NMODL ../Ca.mod
 -> NMODL ../Ih.mod
 -> NMODL ../Im.mod
Translating Ca.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/Ca.c
Translating Ih.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/Ih.c
Thread Safe
Translating Im.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/Im.c
Thread Safe
 -> NMODL ../K_Pst.mod
Thread Safe
 -> NMODL ../K_Tst.mod
 -> NMODL ../Nap_Et2.mod
Translating K_Tst.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/K_Tst.c
Translating K_Pst.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/K_Pst.c
Translating Nap_Et2.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/Nap_Et2.c
Thread Safe
Thread Safe
 -> NMODL ../NaTa_t.mod
Thread Safe
 -> NMODL ../NaTs2_t.mod
 -> NMODL ../ProbAMPANMDA_EMS.mod
Translating NaTa_t.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/NaTa_t.c
Translating NaTs2_t.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/NaTs2_t.c
Thread Safe
Translating ProbAMPANMDA_EMS.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/ProbAMPANMDA_EMS.c
Thread Safe
 -> NMODL ../ProbGABAAB_EMS.mod
 -> NMODL ../SK_E2.mod
Notice: This mechanism cannot be used with CVODE
Notice: A_AMPA discontinuity adjustment not available.
Notice: B_AMPA discontinuity adjustment not available.
Notice: A_NMDA discontinuity adjustment not available.
Notice: B_NMDA discontinuity adjustment not available.
Warning: dt undefined. (declared within VERBATIM?)
Warning: value undefined. (declared within VERBATIM?)
Thread Safe
Translating ProbGABAAB_EMS.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/ProbGABAAB_EMS.c
 -> NMODL ../SKv3_1.mod
Translating SK_E2.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/SK_E2.c
Thread Safe
Notice: This mechanism cannot be used with CVODE
Notice: A_GABAA discontinuity adjustment not available.
Notice: B_GABAA discontinuity adjustment not available.
Notice: A_GABAB discontinuity adjustment not available.
Notice: B_GABAB discontinuity adjustment not available.
Warning: dt undefined. (declared within VERBATIM?)
Warning: value undefined. (declared within VERBATIM?)
Translating SKv3_1.mod into /export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods/x86_64/SKv3_1.c
Thread Safe
 -> Compiling CaDynamics_E2.c
Thread Safe
 -> Compiling Ca_HVA.c
 -> Compiling Ca_LVAst.c
 -> Compiling Ca.c
 -> Compiling Ih.c
 -> Compiling Im.c
 -> Compiling K_Pst.c
 -> Compiling K_Tst.c
 -> Compiling Nap_Et2.c
 -> Compiling NaTa_t.c
 -> Compiling NaTs2_t.c
 -> Compiling ProbAMPANMDA_EMS.c
 -> Compiling ProbGABAAB_EMS.c
 -> Compiling SK_E2.c
 -> Compiling SKv3_1.c
 => LINKING shared library ./libnrnmech.so
 => LINKING executable ./special LDFLAGS are:    -pthread
Successfully created x86_64/special
>>> simulate_cells.compile_all_mechanisms("../../../.config/mearec/1.8.0/cell_models/bbp", verbose=True)
[PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_BP_bAC217_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_BTC_bAC217_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_ChC_cACint209_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_DBC_bAC217_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_LBC_bAC217_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_MC_bAC217_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_NBC_bAC217_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_NGC_bNAC219_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_SBC_bNAC219_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_STPC_cADpyr232_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_TTPC1_cADpyr232_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_TTPC2_cADpyr232_1'), PosixPath('../../../.config/mearec/1.8.0/cell_models/bbp/L5_UTPC_cADpyr232_1')]
/export/home1/users/nsr/wyngaard/.config/mearec/1.8.0/cell_models/bbp/mods
Mod files: "./CaDynamics_E2.mod" "./Ca_HVA.mod" "./Ca_LVAst.mod" "./Ca.mod" "./Ih.mod" "./Im.mod" "./K_Pst.mod" "./K_Tst.mod" "./Nap_Et2.mod" "./NaTa_t.mod" "./NaTs2_t.mod" "./ProbAMPANMDA_EMS.mod" "./ProbGABAAB_EMS.mod" "./SK_E2.mod" "./SKv3_1.mod"

COBJS=''
 -> Compiling mod_func.cpp
 => LINKING shared library ./libnrnmech.so
Successfully created x86_64/special
```

I am on Ubuntu 20.04 LTS, the latest version of MEArec (from Github, 1.8.0), neuron 8.1.0, numpy 1.22.0, scipy 1.8.0, LFPy 2.2.6, I am not using a notebook I am coding via the terminal in python.

Thanks

**Comment by alejoe91** [comment]
Hi @Dradeliomecus 

What python version are you using? Indeed the syntax error looks weird!

**Comment by Dradeliomecus** [comment]
Ah sorry, I forgot the Python version!! 3.8.10

Yeah I tried to understand all morning why I was getting a `SyntaxError`, but I just can't explain it.
I don't know if this is the reason why the template generation is failing (probably, but not sure).

**Comment by alejoe91** [comment]
Fixed via https://github.com/alejoe91/MEArec/pull/107
