### ISSUE TITLE
Generation with a given list of template_ids

### ISSUE THREAD

**Issue by yger** [alejoe91/MEArec#119]
I want to generate two recordings, one with drift, and the same without. To do so, first, I'm generating a drifting recording (because random selection of template is different when drifts are activated). Once this is done, I got a list of templates. Fine for now. However, when trying to generate the same recording without drift (generate_recordings(...., template_ids = template_ids)), then something is clearly wrong. For a list of 25 neurons, MEArec writes: 

'template_ids' is given. Setting n_exc=40 and n_inh=90

Which is clearly wrong (since I have only 25 ids) and then crash after

Traceback (most recent call last):
  File "/home/pierre/github/probe_density/test.py", line 105, in <module>
    recgen = mr.gen_recordings(params=recordings_params, tempgen=tempgen, 
  File "/home/pierre/anaconda3/envs/circus/lib/python3.9/site-packages/MEArec/generation_tools.py", line 145, in gen_recordings
    recgen.generate_recordings(tmp_mode=tmp_mode, tmp_folder=tmp_folder, template_ids=template_ids,
  File "/home/pierre/anaconda3/envs/circus/lib/python3.9/site-packages/MEArec/generators/recordinggenerator.py", line 963, in generate_recordings
    st.annotate(bintype=template_bin[i], mtype=template_celltypes[i], soma_position=template_locs[i])
IndexError: index 25 is out of bounds for axis 0 with size 25

Any hints?

**Comment by yger** [comment]
I made Fix #120 and a PR that I guess solves the problem. Currently, in Mearec, template_ids are ignored in fact....
