### ISSUE TITLE
Exception in in convolve_templates_spiketrains.py

### ISSUE THREAD

**Issue by cristi-zz** [alejoe91/MEArec#15]
Hi! I installed the MEArec library from git, into an anaconda env.
I configured some  paths for templates, spiketrains and recordings.

I ran ```mearec gen-templates -par -p Neuronexus-32-Kampff``` and after a while I got an hdf5 file:
```
Cell: L5_BP_bAC217_1 Progress: [50/50]
Exiting Thread-0
Simulation time:  759.7694327831268 
Saved template generator templates in  ....
Saved eap templates in ....
```
[some white spaces are removed]

Then, I started the gen-recordings like this:

```mearec gen-recordings -m none -md 15 --no-filt -t templates/physrot/templates_50_Neuronexus-32-Kampff_12-12-2018.h5```

where ```templates_50_Neuronexus-32-Kampff_12-12-2018.h5``` is the file generated by ```gen-templates``` command

I got the following error (listing the whole output):
```
NEURON -- VERSION 7.5 master (6b4c19f) 2017-09-25
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2016
See http://neuron.yale.edu/neuron/credits

/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/quantities-0.12.2-py3.6.egg/quantities/quantity.py:321: RuntimeWarning: divide by zero encountered in true_divide
Noise Level  10
/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/MEAutility-1.2.1-py3.6.egg/MEAutility/core.py:266: RuntimeWarning: invalid value encountered in true_divide
  self.normal /= np.linalg.norm(self.normal)
Selecting cells
Padding template edges
Creating time jittering
/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/scipy/signal/signaltools.py:2383: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return y[keep]
/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/scipy/signal/signaltools.py:3463: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return y[sl]
Computing spike train SNR
Adding spiketrain annotations
Convolving with spike  0  out of  20
START: convolution with spike  0
Traceback (most recent call last):
  File "/home/cristi/miniconda3/envs/neurocnn/bin/mearec", line 11, in <module>
    load_entry_point('MEArec', 'console_scripts', 'mearec')()
  File "/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cristi/miniconda3/envs/neurocnn/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/cristi/work/MEArec/MEArec/cli.py", line 312, in gen_recordings
    recgen = generators.gen_recordings(templates=kwargs['templates'], params=params_dict)
  File "/home/cristi/work/MEArec/MEArec/generators.py", line 1055, in gen_recordings
    recgen = RecordingGenerator(spgen, tempgen, params_dict)
  File "/home/cristi/work/MEArec/MEArec/generators.py", line 862, in __init__
    cut_out=cut_outs_samples)
  File "/home/cristi/work/MEArec/MEArec/tools.py", line 1240, in convolve_templates_spiketrains
    raise Exception()
Exception
```

Am I doing something wrong? Thank you!

**Comment by alejoe91** [comment]
Hi @cristi-zz, the template generation ran fine. The call to gen-recordings look ok. Can you try to remove the -m none and tell me if it runs through? I haven't tested that properly yet. 
Cheers
Alessio

**Comment by cristi-zz** [comment]
Hi @alejoe91, I removed the -m parameter and it worked. I got a nice hdf5 file with different content. 
Reading the ```MEArec/tools.py``` file I managed to quickly figure out how to extract:
 - electrode positions [```channel_positions```]
 - Per electrode voltage recordings [```recordings```]

However, I am not sure about:
 - Neuron position? Is it in ```spiketrains/_neuron_no_/annotations``` -> ```soma_position```?  Are the coordinates in the same frame as the electrode positions?
 - When and what neuron fired? Is it in ```spiketrains/_neuron_no_/times```? Are the values seconds or miliseconds?

What are:
 - ```voltage_peaks``` (have the shape (no_neurons, no_electrodes)?
 - ```timestamps```? Is it just an iterator with the milisecond timestamp for the recordings? Can one expects that they are not uniform?
 - ```spike_traces``` is the spike shape of each neurone wrt to time?

Thank you again for your support!

**Comment by alejoe91** [comment]
Hi @cristi-zz, glad that it worked :) can you write another issue regarding the 'none' modulation?

- The 'soma_position' is in the same reference system as the 'channel_positions'.
- The spiketrain 'times' are the firing times (if I remember correctly they are in seconds). Each element contains the firing of one of the neurons.
- 'voltage_peaks' are the potential values at the electrode positions at the peak time (for each neuron)
- 'timestamps' are the recording timestamps and indeed they are uniform
- 'spike_traces' are the convolution only on the electrode with the largest peak for each neuron. Basically a single signal proxy of the extracellular activity

Let me know if anything is still unclear.
Cheers
Alessio
