### ISSUE TITLE
generate_templates_and_recordings Notebook

### ISSUE THREAD

**Issue by McD-NMI** [alejoe91/MEArec#43]
I am trying to run the Jupyter notebook generate_templates_and_recordings. However, when trying to generate new tmeplate, I come across an eerror after running this block of code:

template_params['n'] = 20
template_params['probe'] = 'Neuronexus-32'
comment: the templates are not saved, but the intracellular simulations are saved in 'templates_folder'
tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=templates_params)
comment: this will take a few minutes...

--------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-746fdfbcbc14> in <module>()
      2 template_params['probe'] = 'Neuronexus-32'
      3 # the templates are not saved, but the intracellular simulations are saved in 'templates_folder'
----> 4 tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=templates_params)
      5 # this will take a few minutes...

c:\users\myname\pycharmprojects\excellsim\venv\lib\site-packages\MEArec\generation_tools.py in gen_templates(cell_models_folder, params, templates_tmp_folder, intraonly, parallel, delete_tmp, verbose)
    196                                 delete_tmp=delete_tmp,
    197                                 verbose=verbose)
--> 198     tempgen.generate_templates()
    199 
    200     return tempgen

c:\users\myname\pycharmprojects\excellsim\venv\lib\site-packages\MEArec\generators\templategenerator.py in generate_templates(self)
    186 
    187         tmp_folder = join(templates_folder, rot, 'tmp_%d_%s' % (n, probe))
--> 188         templates, locations, rotations, celltypes = load_tmp_eap(tmp_folder)
    189         if delete_tmp:
    190             shutil.rmtree(tmp_folder)

c:\users\myname\pycharmprojects\excellsim\venv\lib\site-packages\MEArec\tools.py in load_tmp_eap(templates_folder, celltypes, samples_per_cat, verbose)
    144     if verbose:
    145         print("Loading eap data ...")
--> 146     eaplist = [f for f in os.listdir(templates_folder) if f.startswith('eap')]
    147     loclist = [f for f in os.listdir(templates_folder) if f.startswith('pos')]
    148     rotlist = [f for f in os.listdir(templates_folder) if f.startswith('rot')]

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\MyName\\PycharmProjects\\ExCellSim\\notebooks\\physrot\\tmp_50_Neuronexus-32'

**Comment by alejoe91** [comment]
Hi @McD-NMI 
It looks like something failed in the template generation. Can you try to check the terminal from which you opened the notebook? There is probably a Neuron errorerror there. Alternatively, you can run from terminal:

`mearec gen-templates -n 20 -prb Neuronexus-32`

And check the output. Let me know what it says.

Alessio

**Comment by McD-NMI** [comment]
Hi @alejoe91 
Just a note that I have tried this on my work PC with both Anaconda and PyCharm environments, and got the same thing. When I got home, I tried it on my laptop and it worked like a charm. 

I get the same error from trying to run it from terminal with the line of code you sent.


Here is what I get in the terminal... I can't seem to  make sense of it. 


Starting  3


 L5_ChC_cACint209_1 3 / 13


Starting  5


 L5_LBC_bAC217_1 5 / 13

Starting  2


 L5_BTC_bAC217_1 2 / 13



Starting  10


 L5_STPC_cADpyr232_1 10 / 13


Starting  8


 L5_NGC_bNAC219_1 8 / 13


Starting  7


 L5_NBC_bAC217_1 7 / 13


Starting  4
Starting  1


 L5_BP_bAC217_1 1 / 13




 L5_DBC_bAC217_1 4 / 13


Starting  13


 L5_UTPC_cADpyr232_1 13 / 13


Starting  11


 L5_TTPC1_cADpyr232_1 11 / 13


Starting  6


 L5_MC_bAC217_1 6 / 13


Starting  9
Starting  12


 L5_TTPC2_cADpyr232_1 12 / 13




 L5_SBC_bNAC219_1 9 / 13


Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_BTC_bAC217_1
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_LBC_bAC217_1
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
Exiting  2
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_STPC_cADpyr232_1
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_ChC_cACint209_1
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_NGC_bNAC219_1
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_BP_bAC217_1
Exiting  5
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
Exiting  10
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_SBC_bNAC219_1
Exiting  8
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
Exiting  3
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_DBC_bAC217_1
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_UTPC_cADpyr232_1
Exiting  1
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_NBC_bAC217_1
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_TTPC1_cADpyr232_1
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_MC_bAC217_1
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
Traceback (most recent call last):
Exiting  4
Exiting  13
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
Intracellular simulation:  C:\Users\McDonaldMatthew\.config\mearec\cell_models\bbp\L5_TTPC2_cADpyr232_1
Traceback (most recent call last):
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
Traceback (most recent call last):
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    import mpi4py.MPI
Exiting  9
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
ImportError: DLL load failed: The specified procedure could not be found.
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 1062, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, verbose=verbose, **params)
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 307, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
Exiting  6
  File "C:\Users\McDonaldMatthew\Anaconda\lib\site-packages\MEArec\simulate_cells.py", line 101, in return_cell
    import mpi4py.MPI
ImportError: DLL load failed: The specified procedure could not be found.
Exiting  12
Exiting  7
Exiting  11
[I 10:04:38.457 NotebookApp] Saving file at /notebooks/generate_templates_and_recordings.ipynb

**Comment by alejoe91** [comment]
@McD-NMI it seems like an MPI related problem. Can you install it from here: https://www.microsoft.com/en-us/download/details.aspx?id=57467

Let me know if you have other issues or suggestions. 
Alessio

**Comment by McD-NMI** [comment]
@alejoe91 
It works!  Thanks for the help!
