### ISSUE TITLE
problem running gen_templates.py -- NEURON: PyObject method call failed: _declare_contour

### ISSUE THREAD

**Issue by magland** [alejoe91/MEArec#6]
Do you recognize the error below when I am running

```
python gen_templates.py
```
```
NEURON: PyObject method call failed: _declare_contour
 near line 0
 ^
        Import3d_GUI[0].instantiate(cADpyr232_L5_STPC_d16b0be14e[0])
      morphology_d16b0be14e[0].morphology(cADpyr232_L5_STPC_d16b0be14e[0])
    cADpyr232_L5_STPC_d16b0be14e[0].load_morphology()
  cADpyr232_L5_STPC_d16b0be14e[0].init(0)
oc_restore_code tobj_count=2 should be 0
Traceback (most recent call last):
  File "simulate_cells.py", line 764, in <module>
    run_cell_model(cell_model, vm_im_sim_folder, np.random.randint(1, 1000), **params)
  File "simulate_cells.py", line 286, in run_cell_model
    cell = return_cell(cell_model, 'bbp', cell_name, T, dt, 0)
  File "simulate_cells.py", line 164, in return_cell
    verbose=True)
  File "/home/magland/miniconda3/envs/mearec/lib/python2.7/site-packages/LFPy/templatecell.py", line 150, in __init__
    Cell.__init__(self, **kwargs)
  File "/home/magland/miniconda3/envs/mearec/lib/python2.7/site-packages/LFPy/cell.py", line 201, in __init__
    self._load_geometry()
  File "/home/magland/miniconda3/envs/mearec/lib/python2.7/site-packages/LFPy/templatecell.py", line 160, in _load_geometry
    self.template = getattr(neuron.h, self.templatename)(self.templateargs)
RuntimeError: hoc error
```

I am on Ubuntu 16.04, a conda environment. Tried to follow installation instructions. Installed neuron via .deb package.

**Comment by alejoe91** [comment]
Due to neuron 7.5.
Closing this

**Comment by espenhgn** [comment]
Can confirm that the NEURON fix works w. LFPy: https://github.com/LFPy/LFPy/issues/116
