### ISSUE TITLE
Fix dependency on old h5py version 2.10.0

### ISSUE THREAD

**Issue by mahlzahn** [alejoe91/MEArec#80]
I don’t manage to install the old h5py version 2.10.0 which is requested as dependency for mearec. The installation runs with the newest h5py version 3.1.0, but running the program with `mearec gen-templates -prb tetrode-mea-l -n 30 --seed 0` as suggested by paper [1] leads to following error:
```
--------------------------------------------------------------------------------
LokyProcess-5 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/usr/lib/python3.9/site-packages/joblib/externals/loky/backend/queues.py", line 75, in __setstate__
    self._after_fork()
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 69, in _after_fork
    self._reset(after_fork=True)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 73, in _reset
    self._notempty._at_fork_reinit()
AttributeError: '_SafeQueue' object has no attribute '_notempty'


--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/mearec", line 33, in <module>
    sys.exit(load_entry_point('MEArec', 'console_scripts', 'mearec')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rwolff/git/MEArec/MEArec/cli.py", line 180, in gen_templates
    tempgen = gt.gen_templates(cell_models_folder=model_folder,
  File "/home/rwolff/git/MEArec/MEArec/generation_tools.py", line 228, in gen_templates
    tempgen.generate_templates()
  File "/home/rwolff/git/MEArec/MEArec/generators/templategenerator.py", line 212, in generate_templates
    Parallel(n_jobs=n_jobs)(delayed(simulate_cell_templates)(i, simulate_script, tot, cell_model,
  File "/usr/lib/python3.9/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/usr/lib/python3.9/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}
```
I don’t know whether this error is related to the wrong h5py version. But if so, do you have any suggestion?

Btw, it was also complaining about `sh: line 1: nrnivmodl: command not found` but this could be fixed by installation of neuron via `pip install neuron`.

[1] https://doi.org/10.1007/s12021-020-09467-7

**Comment by alejoe91** [comment]
Hi @mahlzahn 

Thanks for the interest in Mearec! I strongly recommend to use anaconda to build an environment that you use for Mearec simulations. I plan to update to the latest h5py and neuron versions soon, but for the time being, I suggest to use python 3.7 and to install Neuron7.7 as outlined here: https://mearec.readthedocs.io/en/latest/installation.html

I'll leave the issue open and close it when Mearec has been updated for the latest neuron and h5py

**Comment by mahlzahn** [comment]
Hi @alejoe91 Thanks for your quick reply!

Unfortunately I still didn’t manage to run with success. I used now anaconda with python 3.7.7 but I am stuck with installing Neuron 7.7, which doesn’t work neither on Ubuntu 20.4 (It is installing, but complaining about missing dependencies) nor on Manjaro (compilation needs interviews, which found only on https://github.com/neuronsimulator/iv but doesn’t install) nor using pip which supports only Neuron 7.8.

Running mearec 1.5.1 with Neuron 7.8, h5py 2.10.0, lfpy 2.1.2 leads to following error message:
```
--No graphics will be displayed.
Warning: no DISPLAY environment variable.
Traceback (most recent call last):
  File "/home/user/.conda/envs/r_env/bin/mearec", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.conda/envs/r_env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.conda/envs/r_env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.conda/envs/r_env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.conda/envs/r_env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.conda/envs/r_env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/MEArec/cli.py", line 187, in gen_templates
    verbose=verbose)
  File "/home/user/.local/lib/python3.7/site-packages/MEArec/generation_tools.py", line 228, in gen_templates
    tempgen.generate_templates()
  File "/home/user/.local/lib/python3.7/site-packages/MEArec/generators/templategenerator.py", line 229, in generate_templates
    raise FileNotFoundError(f'{tmp_folder} not found. Something went wrong in the template generation phase.')
FileNotFoundError: /home/user/.config/mearec/templates/physrot/tmp_30_tetrode-mea-l not found. Something went wrong in the template generation phase.
```

**Comment by alejoe91** [comment]
Hi @mahlzahn 

I haven't tested with Neuron7.8 and I think that is what could be causing the problem. I'll try to update this in the next few weeks.

**Comment by alejoe91** [comment]
The master version (1.7.0) is now compatible with neuron 7.8 and LFPy 2.2!
